version: "3.3"
services:
  cookingapp:
    image: cooking-app
    build:
      context: ./
    networks:
      - app-net
    ports:
      - "3000:3000"

  selenium:
    image: selenium/standalone-firefox
    networks:
      - app-net
    ports:
      - "4444:4444"

  ayespy_report:
    image: nginx
    volumes:
      - /home/playground/ayespy:/usr/share/nginx/html
      - /playground/nginx.conf:/etc/nginx/nginx.conf
    ports:
       - "80:80"
    environment:
      - NGINX_PORT=80

networks:
  app-net:
    driver: overlay
