version: "3.3"
services:
  cookingapp:
    image: cooking-app
    build:
      context: ./
    networks:
      - app-net
    ports:
      - "3000:3000"

  selenium:
    image: selenium/standalone-chrome
    networks:
      - app-net
    ports:
      - "4444:4444"

networks:
  app-net:
    driver: overlay
